# Generated by Django 5.2.3 on 2025-10-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_id',
        ),
    ]
