# Generated by Django 5.0.14 on 2025-11-18 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('account_number', models.CharField(max_length=255, unique=True)),
                ('bank', models.CharField(max_length=255, unique=True)),
                ('account_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pharmacyreferral',
            name='mode_of_payment',
        ),
        migrations.AddField(
            model_name='pharmacyreferral',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_referrals', to='healthManagement.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='drugsale',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_sales', to='healthManagement.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_requests', to='healthManagement.paymentmethod'),
        ),
    ]
