# Generated by Django 5.2.3 on 2025-07-26 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthManagement', '0002_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientEMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('height', models.PositiveSmallIntegerField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Undisclosed')], max_length=1)),
                ('allergies', models.JSONField(blank=True, default=list, help_text='List of allergy names and reactions')),
                ('current_medications', models.JSONField(blank=True, default=list, help_text='Medications with dosage and frequency')),
                ('chronic_conditions', models.JSONField(blank=True, default=list, help_text='Persistent medical conditions')),
                ('surgical_history', models.JSONField(blank=True, default=list, help_text='Past surgical procedures with dates')),
                ('last_blood_pressure', models.CharField(blank=True, help_text="Format: '120/80'", max_length=7)),
                ('last_blood_sugar', models.DecimalField(blank=True, decimal_places=1, help_text='Fasting glucose in mg/dL', max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Electronic Medical Record',
                'verbose_name_plural': 'Electronic Medical Records',
            },
        ),
    ]
