# Generated by Django 5.0.14 on 2025-11-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthManagement', '0002_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
