# Generated by Django 5.2.3 on 2025-10-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthManagement', '0002_remove_appointment_appointment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_doctor_with_patient',
            field=models.BooleanField(default=False),
        ),
    ]
