# Generated by Django 5.0.14 on 2025-11-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthManagement', '0003_alter_paymentmethod_account_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
