# Generated by Django 5.2.3 on 2025-10-26 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthManagement', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='patientemr',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientvital',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientvital',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='pharmacist',
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='room',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='requesting_doctor',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='verified_by',
        ),
        migrations.DeleteModel(
            name='AllocateBed',
        ),
        migrations.DeleteModel(
            name='Drug',
        ),
        migrations.DeleteModel(
            name='PatientEMR',
        ),
        migrations.DeleteModel(
            name='PatientVital',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
