# Generated by Django 5.2.3 on 2025-07-26 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthManagement', '0004_alter_patientemr_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure_systolic', models.PositiveSmallIntegerField(verbose_name='Systolic BP (mmHg)')),
                ('blood_pressure_diastolic', models.PositiveSmallIntegerField(verbose_name='Diastolic BP (mmHg)')),
                ('heart_rate', models.PositiveSmallIntegerField(verbose_name='Heart Rate (bpm)')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Temperature (°C)')),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='SpO2 (%)')),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Respiratory Rate (breaths/min)')),
                ('measurement_context', models.CharField(choices=[('RESTING', 'Resting'), ('POST_EXERCISE', 'Post-Exercise'), ('FASTING', 'Fasting'), ('POST_PRANDIAL', 'After Meal')], default='RESTING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role__name': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_vitals', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, limit_choices_to={'role__name__in': ['doctor', 'nurse']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Vital Signs',
                'verbose_name_plural': 'Patient Vital Signs Records',
                'ordering': ['-recorded_at'],
                'permissions': [('view_all_vitals', 'Can view all patients vitals')],
            },
        ),
    ]
