# Generated by Django 5.2.3 on 2025-08-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthManagement', '0005_patientvital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientemr',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='patientemr',
            name='chronic_conditions',
        ),
        migrations.RemoveField(
            model_name='patientemr',
            name='current_medications',
        ),
        migrations.RemoveField(
            model_name='patientemr',
            name='surgical_history',
        ),
    ]
