# Generated by Django 5.2.3 on 2025-10-26 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthManagement', '0005_remove_prescription_medications_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('temperature_c', models.DecimalField(decimal_places=1, help_text='Body temperature in Celsius', max_digits=4)),
                ('pulse_rate', models.PositiveIntegerField(help_text='Heart rate in beats per minute (bpm)')),
                ('respiratory_rate', models.PositiveIntegerField(help_text='Breaths per minute')),
                ('systolic_bp', models.PositiveIntegerField(help_text='Systolic blood pressure (mmHg)')),
                ('diastolic_bp', models.PositiveIntegerField(help_text='Diastolic blood pressure (mmHg)')),
                ('oxygen_saturation', models.DecimalField(decimal_places=1, help_text='SpO₂ percentage', max_digits=4)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role__name': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_vital_signs', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
