# Generated by Django 5.2.3 on 2025-08-02 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthManagement', '0006_remove_patientemr_allergies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('test_code', models.CharField(max_length=20)),
                ('test_category', models.CharField(choices=[('HEMATOLOGY', 'Hematology'), ('BIOCHEMISTRY', 'Biochemistry'), ('MICROBIOLOGY', 'Microbiology'), ('PATHOLOGY', 'Pathology'), ('RADIOLOGY', 'Radiology'), ('CARDIOLOGY', 'Cardiology')], max_length=20)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('collection_date', models.DateTimeField(blank=True, null=True)),
                ('processing_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('results', models.JSONField(default=dict, help_text='Structured test results data')),
                ('reference_ranges', models.JSONField(blank=True, help_text='Normal reference ranges', null=True)),
                ('abnormal_flags', models.JSONField(blank=True, help_text='Abnormal result indicators', null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='test_reports/%Y/%m/%d/')),
                ('raw_data_files', models.JSONField(blank=True, help_text='Array of raw data file paths', null=True)),
                ('clinical_notes', models.TextField(blank=True, null=True)),
                ('interpretation', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role__name': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_tests', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, limit_choices_to={'role__name': 'labtech'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_tests', to=settings.AUTH_USER_MODEL)),
                ('requesting_doctor', models.ForeignKey(blank=True, limit_choices_to={'role__name': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_tests', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'role__name__in': ['doctor', 'labtech']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_date'],
                'permissions': [('can_process_test', 'Can process lab tests'), ('can_verify_test', 'Can verify test results')],
            },
        ),
    ]
