# Generated by Django 5.2.3 on 2025-08-02 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthManagement', '0008_drug_prescription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={},
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='date_approved',
            new_name='collected_date',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='date_fulfilled',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='date_prescribed',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='fulfilled_by',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescribing_doctor',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='quantity_fulfilled',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='quantity_prescribed',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='status',
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prepared_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name': 'pharmacist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
