# Generated by Django 5.2.3 on 2025-08-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthManagement', '0009_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
