# Generated by Django 5.2.3 on 2025-08-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthManagement', '0011_prescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
