from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(ActiveWebSocketConnection),
admin.site.register(VerificationCode),
admin.site.register(Profile),
admin.site.register(Department),
admin.site.register(Appointment),
admin.site.register(Notification),
admin.site.register(VitalSign),
admin.site.register(MedicalRecord),
admin.site.register(Treatment),
admin.site.register(SurgeryPlacement),
admin.site.register(Bed),
admin.site.register(Room),
admin.site.register(Ward),
admin.site.register(TestRequest),
admin.site.register(TestResult),
admin.site.register(PharmacyReferral),
admin.site.register(Drug),
admin.site.register(DeliveredMedicationTreatment),
admin.site.register(who_administered),
admin.site.register(DoctorVisit),
admin.site.register(DrugSale),
admin.site.register(BulkSaleId),
admin.site.register(ReferralDispensedDrugItem),
admin.site.register(AdmissionCharges),
admin.site.register(Admission),
admin.site.register(TestTypes),
admin.site.register(PaymentMethod),
admin.site.register(AdmissionChargeCategory),

